[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel Cython",
  "/opt/venv/bin/pip install --no-build-isolation -r requirements.txt",
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
